name: CI with manual trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select on which env. to run:'
        required: true
        default: 'staging'
        options: 
        - dev
        - staging
        - prod
      artifacts:
        type: boolean
        required: false
        description: 'Attach Report'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install

        - name: Test on DEV
          if: ${{ github.event.inputs.environment == 'dev'}}
          run: npm run dev
        - name: Test on Staging
          if: ${{ github.event.inputs.environment == 'staging'}}
          run: npm run staging
        - name: Test on Prod
          if: ${{ github.event.inputs.environment == 'prod'}}
          run: npm run prod

        - if: github.event.inputs.artifacts == true
          uses: actions/upload-artifact@v3
          with:
            name: automation-report
            path: reports/index.html
